### ISSUE TITLE
No fuzz introspector report..?

### ISSUE THREAD

**Issue by sebras** [ossf/fuzz-introspector#1033]
Hi

I'm trying to visit: https://storage.googleapis.com/oss-fuzz-introspector/mupdf/inspector-report/20230530/fuzz_report.html

but that page never finishes loading. Am I wrong to expect it to at least give me an error message after several hours?

**Comment by DavidKorczynski** [comment]
Hmm, strange. For me this loads for in a matter of a second or so.

Just tried Brave browser and Edge -- which browser are you using?

**Comment by sebras** [comment]
Ehm, now it took two seconds for me too! Sorry for the noise. :)
