### ISSUE TITLE
Move new fuzzers templates to a separate .html

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#106]
As the current templates are more suggestive and exploratory it can be better to have them in a separate .html and link it in the main report page. This will declutter the main page and it loads faster. WDYT @DavidKorczynski?

**Comment by DavidKorczynski** [comment]
Agreed, sounds good!

**Comment by DavidKorczynski** [comment]
> it loads faster

FYI I think the bottleneck for loading is the various function tables -- these are the components that have a lot of data in them.

**Comment by DavidKorczynski** [comment]
Loading improvements were done here https://github.com/ossf/fuzz-introspector/pull/163 and I removed the suggested fuzzer source codes by default by way of https://github.com/ossf/fuzz-introspector/issues/167 -- the suggestions as they are now are not much to use for a developer as the code does of the fuzzers do not really make sense. As such, it would be nicer to not show them (and confuse the user) for the OSS-Fuzz v1. The optimal targets are the important artifacts and they remain, as well as the rest of the optimal targets analysis.

Am closing this one for those reasons, please re-open if you have concerns.
