### ISSUE TITLE
web: function-arguments type should be JSON encoded

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#1187]
From e.g. https://introspector.oss-fuzz.com/api/far-reach-but-low-coverage?project=libucl

```
"function-arguments":"['struct.ucl_parser *', 'char *', 'int ', 'int ', 'int ']"
```

The `function-arguments` value seems to be string encoded as a Python literal. We should just make this a JSON array instead.

**Comment by oliverchang** [comment]
CC @DavidKorczynski

**Comment by oliverchang** [comment]
A different issue: Is it possible to also get the original typedef for these types instead of the actual type it refers to? 

E.g. preferring `ucl_object_t` over `struct.ucl_object_s *`.

**Comment by jonathanmetzman** [comment]
Also, not for now,  but I think there are some inconsistencies where some fields use underscores and others uses hyphens.

**Comment by DavidKorczynski** [comment]
> A different issue: Is it possible to also get the original typedef for these types instead of the actual type it refers to?
> 
> E.g. preferring `ucl_object_t` over `struct.ucl_object_s *`.

Not using the set up we currently have. The `ucl_object_t` is not present in the LLVM data we use. What we have is a reference to `ucl_object_t` being declared as a alias for `struct ucl_object_s`, however, we don't have information that this particular typedef is used in the function argument.

We may be able to do some, bit hacky stuff, by making a quick lookup of the file itself and see if the types match.

Ideally, we should, however, add another stage in the analyses that is based purely on the AST. This would probably be the right solution long term.

How high priority would this be?
