### ISSUE TITLE
REST-API interface is very inconsistent

### ISSUE THREAD

**Issue by silvergasp** [ossf/fuzz-introspector#1318]
I've been trying to write a client library in rust for the [introspector rest-api](https://introspector.oss-fuzz.com/api#api-far-reach-but-low-coverage). While doable, I've found the process a little frustrating. Here are some of the issues I've found with it;
- Inconsistent use of underscores/dashes, e.g. function-name and function_filename.
- The result field is not consistent between endpoints e.g. 'far-reach-but-low-coverage', returns  "succes" in the result field. Whereas the project summary returns "success" in the result field.

**Comment by DavidKorczynski** [comment]
That sounds awesome, I'd love to follow along, is it public?

Naming and conventions should be standardized, I agree.

I think it may make sense to define something more concrete for the API, e.g. a spec of sort that can be utilized, either via protobuf or similar.

**Comment by silvergasp** [comment]
So far it's part of a private project. But I'd be happy to spin that component out into an open-source project, if there is interest.

**Comment by silvergasp** [comment]
@DavidKorczynski Client lib here, need to add some docs and create a crates.io package but you should be able to get an idea how to use it from the examples directory. It is pretty much feature complete in terms of querying the API.

**Comment by silvergasp** [comment]
Crate docs here are here [fuzz-introspector-client](https://docs.rs/fuzz-introspector-client/latest/fuzz_introspector_client/).

**Comment by DavidKorczynski** [comment]
Cool, thanks for the links @silvergasp

I might approach this in a two-step approach: first fix up so naming and conventions are consistent; then come up with some specification which can be used for serialization across languages.

**Comment by silvergasp** [comment]
Sounds reasonable to me, protobuf/grpc sounds nice.

**Comment by DavidKorczynski** [comment]
I've adjusted things now in the referenced PR.

This should have an effect in around ~18 hours. There'll be a JSON schema for each API and they will be visible on the API page, in summary changed all `-` to `_` and fixed some typos.

https://github.com/silvergasp/fuzz-introspector-client will have to be changed -- I'll ping here when the updated webapp is live.

**Comment by DavidKorczynski** [comment]
This should be good now @silvergasp !

I think for now we'll stay with JSON shemas to keep things light.

**Comment by oliverchang** [comment]
One more inconsistency. "src_file" vs "source_file". Would it make sense to fix that too?
