### ISSUE TITLE
Avoid suggesting interesting functions outside the subject project

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#149]
I noticed Fuzz introspector may suggest new fuzz targets from linked libraries. It does not seem productive as the user is intending to fuzz the subject project.

Here is an example for `libarchive` where targets from `libxml2` are being suggested as well:

https://storage.googleapis.com/oss-fuzz-introspector/libarchive/inspector-report/20220321/fuzz_report.html#Remaining-optimal-interesting-functions

<img width="879" alt="Screen Shot 2022-03-23 at 11 23 19 AM" src="https://user-images.githubusercontent.com/19780488/159769730-70d04e99-33c1-40a5-8df9-62348f94f9d4.png">

**Comment by DavidKorczynski** [comment]
I think this is perhaps a duplicate/related of https://github.com/ossf/fuzz-introspector/issues/116 ? I don't think that fuzz-introspector should try and automatically analyse what corresponds the code that matters to the users, instead the users should specify themselves what matters, and one goal is to exclude functions from third parties. It's now possible to exclude functions using a config file https://github.com/ossf/fuzz-introspector/blob/068070c57dcf837c4b222cdd063d22a82d5e2cd8/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp#L255

**Comment by DavidKorczynski** [comment]
Also see the references of that issue, e.g. https://github.com/ossf/fuzz-introspector/issues/35#issue-1125806643

**Comment by Navidem** [comment]
> Also see the references of that issue, e.g. [#35 (comment)](https://github.com/ossf/fuzz-introspector/issues/35#issue-1125806643)

Nice, that make sense.
