### ISSUE TITLE
Introspector Builds Failing for all OSS-Fuzz Python Projects Since 2024-04-23

### ISSUE THREAD

**Issue by DaveLak** [ossf/fuzz-introspector#1511]
On 2024-04-23 Coverage.py shipped version 7.5.0 which included a change that has been causing Python project builds to fail with an unhandled `KeyError: 'relative_filename'` on line 313 of `fuzz_introspector/utils.py`:

https://github.com/ossf/fuzz-introspector/blob/fa833a2bd865ee9ec793802b814c3ec7e43e01cf/src/fuzz_introspector/utils.py#L313

See the `requests` project's build logs for example: https://oss-fuzz-build-logs.storage.googleapis.com/log-5e6353e4-bbc3-4236-bf91-00af0b41c65a.txt

<details><summary>Stack trace from the `requests` projects build logs</summary>

```shell
Traceback (most recent call last):
  File "/fuzz-introspector/src/main.py", line 154, in <module>
    main()
  File "/fuzz-introspector/src/main.py", line 138, in main
    return_code = commands.run_analysis_on_dir(
  File "/fuzz-introspector/src/fuzz_introspector/commands.py", line 65, in run_analysis_on_dir
    html_report.create_html_report(introspection_proj, analyses_to_run,
  File "/fuzz-introspector/src/fuzz_introspector/html_report.py", line 717, in create_html_report
    html_all_function_section) = create_section_all_functions(
  File "/fuzz-introspector/src/fuzz_introspector/html_report.py", line 610, in create_section_all_functions
    all_functions_json_report) = create_all_function_table(
  File "/fuzz-introspector/src/fuzz_introspector/html_report.py", line 88, in create_all_function_table
    func_cov_url = proj_profile.resolve_coverage_report_link(
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/project_profile.py", line 204, in resolve_coverage_report_link
    return self.profiles[0].resolve_coverage_link(
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 151, in resolve_coverage_link
    return utils.resolve_coverage_link(cov_url, source_file, lineno,
  File "/fuzz-introspector/src/fuzz_introspector/utils.py", line 313, in resolve_coverage_link
    (fl, data['files'][fl]['index']['relative_filename']))
KeyError: 'relative_filename'
```

</details> 

@DavidKorczynski, is the code that's erroring still necessary/used? There is a comment a few lines above that begins "`Temporarily for debugging purposes. TODO: David remove this later`":

https://github.com/ossf/fuzz-introspector/blob/fa833a2bd865ee9ec793802b814c3ec7e43e01cf/src/fuzz_introspector/utils.py#L296-L303

**Links to Coverage Release Notes**:
- [Coverage.py change log](https://coverage.readthedocs.io/en/7.5.0/changes.html#version-7-5-0-2024-04-23)
- GitHub Release Page https://github.com/nedbat/coveragepy/releases/tag/7.5.0

---

On a related note, I've always found it curious that Coverage.py is pinned to a v6 release in OSS-Fuzz but installed at the latest available version in Fuzz Introspector. Is that intentional?

**Comment by oliverchang** [comment]
@DavidKorczynski anyone from your side who can help take a look?

**Comment by DavidKorczynski** [comment]
Fix for this in: https://github.com/google/oss-fuzz-gen/pull/243

**Comment by DavidKorczynski** [comment]
> I've always found it curious that Coverage.py is pinned to a v6 release in OSS-Fuzz but installed at the latest available version in Fuzz Introspector. Is that intentional?

Good point, and no it's not intentional. For now, I prefer to pin the coveragepy version in the `base-runner` to be the same as the one used in the `base-builder` on OSS-Fuzz

**Comment by DavidKorczynski** [comment]
Confirming the Python builds are back working since 7th May. I pinned the base-runner in OSS-Fuzz to use the same version of coveragepy as the base-builder. Thanks again @DaveLak
