### ISSUE TITLE
Runtime coverage analysis section always empty?

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#154]
I can't seem to find any reports on https://oss-fuzz-introspector.storage.googleapis.com/ with this section filled. 

Is this working at all?

**Comment by DavidKorczynski** [comment]
Fixed in https://github.com/ossf/fuzz-introspector/commit/a8c08fcd0a03265254edf35c944cf96320376512

**Comment by DavidKorczynski** [comment]
Nothing wrong with the OSS-Fuzz integration -- this was an issue from fuzz-introspector
