### ISSUE TITLE
refine fuzz blocker definition

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#254]
In some projects with good coverage but a few red nodes e.g. 1 or 2 consecutive nodes we currently set fuzz blockers to be there. It's a bit misleading in the sense that not a lot is blocked -- it may simply be missing coverage of a node due to an error check, e.g.
```
void *v = malloc(123);
if (v == NULL) {
  printf("error");
  exit(0);
}
```
here a fuzz can be identified as is if there is not much blocking elsewhere. But it's not really interesting and can be misleading. For something to be considered a blocker it should block a bit more code

**Comment by Navidem** [comment]
Yes, totally agreed. These cases are covered by branch level blocker detection which I am currently working on. Will share initial results soon.
I suggest you hold off on making further changes in the current implementation to avoid redundant efforts.

**Comment by DavidKorczynski** [comment]
sounds good
