### ISSUE TITLE
clang-14: error: unsupported argument 'introspector' to option 'fsanitize='

### ISSUE THREAD

**Issue by ohofox** [ossf/fuzz-introspector#257]
I try to use fuzz-introspector with oss-fuzz, but it reports a build error:
```
clang -O1 -fPIC -D_LARGEFILE64_SOURCE=1 -o minigzip64 minigzip64.o -L. libz.a
+ clang++ -fsanitize=introspector -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -flegacy-pass-manager -flto -fno-inline-functions -fuse-ld=gold -Wno-unused-command-line-argument -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I. /src/bad_example_fuzzer.cc -o /out/bad_example_partial_instrumentation -fsanitize=fuzzer ./libz.a
clang-14: error: unsupported argument 'introspector' to option 'fsanitize='
ERROR:root:Building fuzzers failed.

```
The base-builder image I use is
```
gcr.io/oss-fuzz-base/base-builder      introspector   d22562c68a6c   5 hours ago      1.79GB
gcr.io/oss-fuzz-base/base-builder      latest         d22562c68a6c   5 hours ago      1.79GB
```
Also I notice that the `sanitizer` option in 
`run_both.sh:21 python3 ./infra/helper.py build_fuzzers --sanitizer=introspector $1` 
and 
`run_second_half.sh:20 python3 ./infra/helper.py build_fuzzers --sanitizer=instrumentor $1`
are not the same. 
These options are not correctly set.

**Comment by DavidKorczynski** [comment]
What OSS-Fuzz project are you trying to build here? `-fsanitize=introspector` should not happen -- `introspector` is not an option to clang, rather, `introspector` is an option to `helper.py` in OSS-Fuzz.

**Comment by ohofox** [comment]
It's bad_example, in the projects/bad_example/build.sh script, the commands are like this
```
     42 $CXX -fsanitize=$SANITIZER $CXXFLAGS_ORIG -std=c++11 -I. \
     43     $SRC/bad_example_fuzzer.cc -o $OUT/bad_example_partial_instrumentation \
     44     $LIB_FUZZING_ENGINE ./libz.a
```
The flag `$SANITIZER` which is `introspector` here, is passed to `-fsanitize`.

**Comment by DavidKorczynski** [comment]
> It's bad_example, in the projects/bad_example/build.sh script, the commands are like this
> 
> ```
>      42 $CXX -fsanitize=$SANITIZER $CXXFLAGS_ORIG -std=c++11 -I. \
>      43     $SRC/bad_example_fuzzer.cc -o $OUT/bad_example_partial_instrumentation \
>      44     $LIB_FUZZING_ENGINE ./libz.a
> ```
> 
> The flag `$SANITIZER` which is `introspector` here, is passed to `-fsanitize`.

Thanks! This is an issue in bad_example. I have add a fix here: https://github.com/google/oss-fuzz/pull/7706

**Comment by DavidKorczynski** [comment]
bad_example is now fixed on the OSS-Fuzz side https://github.com/google/oss-fuzz/pull/7706 let me know if this works for you now!

**Comment by DavidKorczynski** [comment]
Closing this as it has now been resolved
