### ISSUE TITLE
Exception in focus function section causes build failure

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#278]
For `tarantool`, here is the log:

https://oss-fuzz-build-logs.storage.googleapis.com/log-507b4d63-a7cb-4228-8e8c-bc7c54334a05.txt

**Comment by Navidem** [comment]
same is for `fio`

**Comment by DavidKorczynski** [comment]
Should be fixed in https://github.com/ossf/fuzz-introspector/pull/261 I believe -- We should run the tests and if all works we can update oss-fuzz

**Comment by DavidKorczynski** [comment]
This should be fixed -- I ran both `tarantool` and `fio` locally and found no issues. Once https://github.com/google/oss-fuzz/pull/7774 is merged on OSS-Fuzz we should see them switch.
