### ISSUE TITLE
Make calltree colormap more informative

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#283]
The colormap is useful to draw attention to the blockage points in the fuzz target calltree. 

![image](https://user-images.githubusercontent.com/19780488/170800441-a8ba6666-3541-4c04-aa2e-af6e933b8b2c.png)

The numbers on the y axis has no information to convey so have to be removed. For the x axis let's use an informative label like: "Calltree Index". Also the color coding should be mentioned: 
Red: not-covered
Green: convered
Yellow: ?? (am not sure about the meaning)

**Comment by DavidKorczynski** [comment]
> Red: not-covered
> Green: convered
> Yellow: ?? (am not sure about the meaning)

Yellow is essentially "hit, but only hit a few times". See https://github.com/ossf/fuzz-introspector/issues/2 This was partly inspired by the OSS-Fuzz coverage reports

**Comment by DavidKorczynski** [comment]
e.g. the coverage reports:

![Screenshot from 2022-05-28 13-03-54](https://user-images.githubusercontent.com/657617/170824677-0bb50f07-d449-4db9-a5c9-73b151f19f38.png)

**Comment by Navidem** [comment]
> > Red: not-covered
> > Green: convered
> > Yellow: ?? (am not sure about the meaning)
> 
> Yellow is essentially "hit, but only hit a few times". See #2 for details
> 
> This was partly inspired by the OSS-Fuzz coverage reports

Thanks for clarification, it makes sense to add this to our [doc](https://github.com/ossf/fuzz-introspector/blob/main/doc/Calltree.md).
