### ISSUE TITLE
Support multiple cores in runtime analysis

### ISSUE THREAD

**Issue by swirsz** [ossf/fuzz-introspector#302]
When running locally, large projects would benefit from libfuzzer being called with multiple cores.  To test this, I modified run_fuzzer in get_full_coverage.py with "-workers=n -jobs=n" and used psutil.cpu_count().

capstone 80: (default setup)
real	19m7.849s
user	0m1.883s
sys	    0m5.875s
LOC 48.26% (126880/262901)

capstone 800: (default setup)
real	33m1.631s
user	0m2.590s
sys	    0m16.393s
LOC 88.64% (268790/303248)

capstone 80: (32 cores)
real	19m37.386s
user	0m3.986s
sys	    0m8.049s
LOC 90.62% (274815/303248)

LOC obtained from corpus/inspector-report/covreport/linux/report.html

**Comment by DavidKorczynski** [comment]
This is fair and I think we should add this.

However, perhaps nicer is to enable the use of existing corpus rather than running the fuzzer to generate corpus.

**Comment by DavidKorczynski** [comment]
Would you be able to assist her with the implementation?

What we need to do is enable `get_full_coverage.py` to pass arbitrary commands to `run_fuzzer` here:
https://github.com/ossf/fuzz-introspector/blob/7493818cc99dd6ca85d81e81d0cda23375e3b303/oss_fuzz_integration/get_full_coverage.py#L105-L116

if you open a PR with an initial suggestion then I'll be happy to assist

**Comment by Navidem** [comment]
This is interesting @swirsz, thanks!

**Comment by DavidKorczynski** [comment]
Fixed by https://github.com/ossf/fuzz-introspector/pull/318
