### ISSUE TITLE
All links redirect to localhost, even if the host is remote

### ISSUE THREAD

**Issue by MarcoFalke** [ossf/fuzz-introspector#33]
Steps to reproduce: http://5.161.44.243:8008/fuzz_report.html

The links are of the form `<a href="http://localhost:8008/covreport/linux/src/brotli/c/dec/huffman.c.html#L172">`.

However, they should be `<a href="/covreport/linux/src/brotli/c/dec/huffman.c.html#L106">`.

**Comment by DavidKorczynski** [comment]
great catch - this should be solvable by modifying the default here: https://github.com/ossf/fuzz-introspector/blob/main/post-processing/main.py#L64

Could you try if that works?

**Comment by DavidKorczynski** [comment]
This commit https://github.com/ossf/fuzz-introspector/commit/442938deb8066eb5b20d464f2c7f84165bafd211 fixes it. Closing, but please reopen if the issue persists!
