### ISSUE TITLE
branch profiler: branches with 0 blocked_reachable_complexity and 0 blocked_not_covered_complexity?

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#356]
looking at https://storage.googleapis.com/oss-fuzz-introspector/arrow/inspector-report/20220627/summary.json, I see some branch blockers with:

`"blocked_not_covered_complexity": 0, "blocked_reachable_complexity": 0`

Is this correct? If they are, do they still make sense to be included in this list?

**Comment by Navidem** [comment]
> Is this correct? If they are, do they still make sense to be included in this list?

This is not necessarily incorrect. What may happen is that the static analysis may fail to identify the callees or collect complexity for the identified callees. So the branch blocker has no source of information to compare such blocked branch sides, but it has identified the side is blocked as the coverage reports shows not hit for it. Therefore, I still want these cases to be reported as it is informative in terms of blockage.

That said, I will debug this specific case of `arrow` and post the update.
