### ISSUE TITLE
New failures for bzip2 project

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#36]
Just noticed that previously successful project bzip2 is failing when .covreport files are present.

[log-bd2b33d6-b7fc-45f7-8041-32f1826e2768.txt](https://github.com/ossf/fuzz-introspector/files/8026778/log-bd2b33d6-b7fc-45f7-8041-32f1826e2768.txt)

**Comment by Navidem** [comment]
Happening the same for igraph:
[log-6e08057d-4c41-4e7d-9819-7582bd58dfb3.txt](https://github.com/ossf/fuzz-introspector/files/8026906/log-6e08057d-4c41-4e7d-9819-7582bd58dfb3.txt)

**Comment by Navidem** [comment]
Another instance for boost:
[log-39a0b375-5ac8-4525-bb3f-5653373d4125.txt](https://github.com/ossf/fuzz-introspector/files/8026914/log-39a0b375-5ac8-4525-bb3f-5653373d4125.txt)

**Comment by DavidKorczynski** [comment]
ah, this was a typo on my part. Thanks! Fixed in https://github.com/ossf/fuzz-introspector/commit/9a94bce9ecb6d46e7f5bf77a6d9c70101d97bd1b
