### ISSUE TITLE
[OSS-Fuzz] Incorrect coverage link for some projects

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#362]
The coverage link on the portal is broken for some projects. [Opencv](https://storage.googleapis.com/oss-fuzz-introspector/opencv/inspector-report/20220629/fuzz_report.html) is an example (also `c-ares`).

The issue is appending one extra `/` to the base `coverage_url`:
https://storage.googleapis.com/oss-fuzz-coverage/opencv/reports/20220629/linux//src/opencv/modules/imgcodecs/src/grfmt_webp.cpp.html#L236

**Comment by oliverchang** [comment]
Could we add a test for this as well when we fix it?

**Comment by Navidem** [comment]
> The issue is appending one extra `/` to the base `coverage_url`:

The source files are coming with extra `/` from the LLVM pass in `fuzzerLogFile`:

```
functionSourceFile: '//src/opencv/modules/imgproc/src/drawing.cpp'
```

Easy fix is sanitizing it in post-process once loaded from profile. But still not sure how for some projects the source files are extract like that.

**Comment by Navidem** [comment]
This can be the culprit:
https://github.com/ossf/fuzz-introspector/blob/9bf86ab4c03c78f44ea9671f364f53ed32a10f4d/llvm/lib/Transforms/FuzzIntrospector/FuzzIntrospector.cpp#L550-L554

Have not check yet, but the seems the `CurrentDir->append("/");` should be inside `if` statement.
