### ISSUE TITLE
numeric metric for calltree bitmap? 

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#406]
It may be useful for devs to compare the improvements they made wrt calltree bitmap. Right now the only way to do this is to eyeball the colouring on the report. 

Would it make sense to add a percentage value here?

**Comment by Navidem** [comment]
Good point to have a machine readable metric here. To be more precise, you are referring to this color map for extracting a numerical digest, right?

![image](https://user-images.githubusercontent.com/19780488/180132101-937a7892-6ef0-444c-b898-de4f061e4950.png)

**Comment by oliverchang** [comment]
yep!

**Comment by DavidKorczynski** [comment]
The Runtime coverage analysis shown for each fuzzer gives a percentage of what is covered at runtime wrt to the statically reachable code for the given fuzzer, which is a numeric metric representation of the data shown in the calltree. 
![Screenshot from 2022-07-21 11-41-06](https://user-images.githubusercontent.com/657617/180195291-c42caf75-35a4-461f-beb8-66f74ca38a72.png)

Does this capture what you're looking for?

**Comment by DavidKorczynski** [comment]
Related to this, it might be nice to include some form of historical data in fuzz introspector (i.e. data from many coverage analysis runs and/or static analysis runs) so that we can do data analysis on progress/deterioration.

**Comment by oliverchang** [comment]
> 

Thanks, it wasn't clear to me that this was the same metric -- i.e. is that number talking about functions or call sites?

**Comment by oliverchang** [comment]
@DavidKorczynski would it make sense to clarify this part in the UI? Is this measuring covered functions / reachable functions or covered callsites / reachable callsites? Or am I horribly misunderstanding something here?

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski would it make sense to clarify this part in the UI? 

It would. I'm working on improving doc and user experience these days. Will try to make this more intuitive.

> Is this measuring covered functions / reachable functions or covered callsites / reachable callsites? Or am I horribly misunderstanding something here?

The representation I showed is missing functions and not callsites which is what the calltree represents, which is what the bitmap shows. On that note I agree we should get a numeric representation of the callsites. Good catch.

**Comment by DavidKorczynski** [comment]
https://github.com/ossf/fuzz-introspector/pull/420 fixes this in the following way:
![Screenshot from 2022-07-29 16-21-53](https://user-images.githubusercontent.com/657617/181791946-651f1aa3-0467-4499-827e-7d4651f5d29d.png)
The border around the colored text is needed as otherwise the yellow can be difficult to see -- the design may need some improvements later. However, it adds numeric metric for the calltree.

**Comment by DavidKorczynski** [comment]
Minor update, to also show the percentage:

![Screenshot from 2022-07-29 16-41-48](https://user-images.githubusercontent.com/657617/181795410-9c44329f-04e2-46de-b8b9-184ef6166e76.png)
