### ISSUE TITLE
bump oss-fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#412]
We should bump OSS-Fuzz as a reasonbly high number of changes has happened since last bump. There was a slight change in the way post-processing unit is called, so a few minor things need change in OSS-Fuzz besides bumping the LLVM number.

@Navidem @AdamKorcz do you have anything that you would like to complete before bumping on OSS-Fuzz side?

**Comment by DavidKorczynski** [comment]
we actually dont have to update the diffs as they are mainly concerned with Python. So only very minor or no diffs are needed except for the commit bump

**Comment by Navidem** [comment]
is the only change regarding post-process for OSS-Fuzz at this line?

`  python3 /fuzz-introspector/post-processing/main.py report $REPORT_ARGS`

**Comment by Navidem** [comment]
and this too:

`python3 /fuzz-introspector/post-processing/main.py correlate --binaries_dir=$OUT/`

**Comment by Navidem** [comment]
re concerns on bump, I just wanted to have the bump after the summit as I will not be available to fix potential failures on OSS-Fuzz side.

**Comment by DavidKorczynski** [comment]
I think so. All of the logic in `compile_python_fuzzer` is irrelevant right now, and all of the logic here https://github.com/ossf/fuzz-introspector/blob/46fa3bb3197c1902e52a1ad698a71f9d248a01a9/oss_fuzz_integration/oss-fuzz-patches.diff#L62-L69 is also irrelevant and all of the logic for enabling python to be used with fuzz introspector is irrelevant.

I would say try the changes you suggest and if https://github.com/ossf/fuzz-introspector/tree/main/oss_fuzz_integration#testing-before-bumping-oss-fuzz passes then we're good

**Comment by DavidKorczynski** [comment]
@AdamKorcz are there any UI leftovers that should be addressed before bumping on OSS-Fuzz?

**Comment by AdamKorcz** [comment]
> @AdamKorcz are there any UI leftovers that should be addressed before bumping on OSS-Fuzz?

No

**Comment by Navidem** [comment]
> I would say try the changes you suggest and if https://github.com/ossf/fuzz-introspector/tree/main/oss_fuzz_integration#testing-before-bumping-oss-fuzz passes then we're good

let's have https://github.com/ossf/fuzz-introspector/pull/411 merged, then I can test.

**Comment by DavidKorczynski** [comment]
> 

ah yes. I think this one would be quite nice to complete. I will do this today.

**Comment by DavidKorczynski** [comment]
Note that `test_projects.py` will fail for `wuffs` as `wuffs` build is currently failing: https://oss-fuzz-build-logs.storage.googleapis.com/log-9aaac143-2250-4fd2-b86b-61e178eae971.txt

**Comment by DavidKorczynski** [comment]
> > @DavidKorczynski There are the descriptions in the high-level overviews.
> 
> ah yes. I think this one would be quite nice to complete. I will do this today.

This is now done. I'm good with bumping on OSS-Fuzz now.

**Comment by Navidem** [comment]
Test for could build is remaining, I will be slow to respond for the rest of the week, attending a team summit.

**Comment by Navidem** [comment]
Done via https://github.com/google/oss-fuzz/pull/8078
