### ISSUE TITLE
Provide a way to check line hit when coverage type is not file

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#441]
The function is its current implementation does not do what it is supposed to for C/C++ coverage.

More specifically `self._cov_type` is not set and `self.file_map` is not populated for such coverages to be used here.
I can take a pass on it on Monday.

**Comment by DavidKorczynski** [comment]
`Coverageprofile.is_file_lineno_hit` was developed with only Python targets in mind and the general idea was to keep it close to the data as its represented by the underlying runtime coverage data https://github.com/ossf/fuzz-introspector/blob/main/doc/LanguageImplementation.md#integrate-code-coverage-collection

`code_coverage.py` is moving towards an API-like module. The benefit of adding C/C++ support is the API will be cleaner but we may end up including abstractions on the coverage that's not extracted from the coverage data -- which is not inherently negative but it may make the `code_coverage.py` module less independent.

Can you elaborate on the specific problem to solve? Does the current APIs from `get_hit_summary` and `get_hit_details` not suffice?

**Comment by Navidem** [comment]
> `Coverageprofile.is_file_lineno_hit` was developed with only Python targets in mind

Now I see why it is checked for `file` type coverage.

> Can you elaborate on the specific problem to solve?

We need to check an exact line for the coverage hit when reporting blockers.

I made an equivalent function for function-based coverage (C/C++) to serve the purpose I was looking for in #445
