### ISSUE TITLE
test for ensuring all links are to files and not directories

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#442]
https://github.com/ossf/fuzz-introspector/issues/427 happened because we had a link to `https://storage.googleapis.com/oss-fuzz-coverage/bluez/reports/20220807/linux` instead of `https://storage.googleapis.com/oss-fuzz-coverage/bluez/reports/20220807/linux/report.hml`. The first link works locally but not on google cloud, as google cloud won't do the redirection to `report.html`. The problem is that all of the links to `storage.googleapis.com/....` should be to files rather than directories. The issue was fixed by https://github.com/ossf/fuzz-introspector/pull/435

It would be nice with a unit test that goes through the full procedure by calling https://github.com/ossf/fuzz-introspector/blob/5ef042b9a5b5dc6de3ce9315d989dedf58fd66a2/src/fuzz_introspector/commands.py#L38 

with proper `.yaml` and `.yaml.data` files and ensures all links to google cloud storage are valid google cloud storage links.

**Comment by DavidKorczynski** [comment]
@arthurscchan could you take a look at this?

**Comment by arthurscchan** [comment]
Got it. Start looking at it.

**Comment by arthurscchan** [comment]
Pull Request #443 create an initial unit testing attempt to solve this problem. It also leave certain flexibilities to extend to more file checking.

**Comment by arthurscchan** [comment]
Currently, there is a new subfolder created inside the test folder, named as **TestReport**.
Inside **Test report**, there is a config.properties file and a bunch of subfolders.

Each subfolders represent one fuzzer project result which includes their **FuzzerLogFile.data** and **FuzzerLogFile.data.yaml**

The config.properties sets the properties for each of the project required this unit testing. with the base folder of each project and specific language specified for future extension.

**Comment by arthurscchan** [comment]
Currently, the unit testing only handle the **fuzz_report.html** file, commented code in the unit testing file showing how it could expand to search all files ends with .html, or even extending to js or css file in a later stage.

**Comment by arthurscchan** [comment]
Currently, the unit testing with dig up all links in the html which is encapsulated in a href tag.

Links start with '#' '?' are ignored because it points to the current file.
Links start with 'http' and not start with "https://storage.googleapis.com/" are also ignored as they are out of scope link.
Other links, including relative links are being checked one by one to ensure it is pointing to a file instead of a directories.

**Comment by arthurscchan** [comment]
> #427 happened because we had a link to `https://storage.googleapis.com/oss-fuzz-coverage/bluez/reports/20220807/linux` instead of `https://storage.googleapis.com/oss-fuzz-coverage/bluez/reports/20220807/linux/report.hml`. The first link works locally but not on google cloud, as google cloud won't do the redirection to `report.html`. The problem is that all of the links to `storage.googleapis.com/....` should be to files rather than directories. The issue was fixed by #435
> 
> It would be nice with a unit test that goes through the full procedure by calling
> 
> https://github.com/ossf/fuzz-introspector/blob/5ef042b9a5b5dc6de3ce9315d989dedf58fd66a2/src/fuzz_introspector/commands.py#L38
> 
> with proper `.yaml` and `.yaml.data` files and ensures all links to google cloud storage are valid google cloud storage links.

I assume you mean `.data` and `.data.yaml` instead.

**Comment by arthurscchan** [comment]
Additional regression testing for Issue #427 has been added.

**Comment by DavidKorczynski** [comment]
@arthurscchan I don't think https://github.com/ossf/fuzz-introspector/pull/443 solved it fully. Cold you please check the comment here https://github.com/ossf/fuzz-introspector/pull/443#issuecomment-1208495885

**Comment by DavidKorczynski** [comment]
I just ran the test locally where I undo the changes in https://github.com/ossf/fuzz-introspector/pull/435 and the test catches them! Very nice @arthurscchan !
