### ISSUE TITLE
"per-fuzzer coverage" seems to be hidden behind "table of contents" with more than one fuzz target

### ISSUE THREAD

**Issue by evverx** [ossf/fuzz-introspector#457]
It was originally reported in https://github.com/ossf/fuzz-introspector/issues/452 but at the time I wasn't sure whether it was a real issue because I ran into it locally with a couple of fuzz targets I added and built with `run_both.sh`. I went to https://storage.googleapis.com/oss-fuzz-introspector/elfutils/inspector-report/20220812/fuzz_report.html and was able to reproduce the issue by clicking on "per-fuzzer coverage"

![Screenshot 2022-08-13 at 04 59 03](https://user-images.githubusercontent.com/10195800/184465604-fdf150c6-d804-47db-a6b7-acdcbc53334c.png)

It was Chrome Version 104.0.5112.79 (Official Build) (x86_64)

**Comment by AdamKorcz** [comment]
Thank you for the report. This should be fixed in https://github.com/ossf/fuzz-introspector/pull/466
