### ISSUE TITLE
Add guidance and conclusions to top of fuzz-introspector report

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#46]
Currently the fuzz-introspector report is focused around displaying a lot of data, but we don't provide a ton of conclusions about the health of the fuzzing of a project.

It would be nice to create some simple conclusions that are easily digestible by a developer, e.g.
- "Your fuzzers have a lot of reachability but the coverage is not matching. You shuold debug the existing fuzzers to improve results"
- "Your fuzzers are all explored well relative to their reachability, you shuold see into adding new fuzzers"
- "This fuzzer is blocked at a specific point: you should try and debug it here"
- "This part of your code is not reached at all, you should see into creating fuzzers that target this code".

This is quite similar in nature to how malware analysis reports will often have a set of heuristics at the top of it which makes it easy to get a holistic view into the malware analysis. We should create something similar for fuzz-introspector.

**Comment by DavidKorczynski** [comment]
The use of color schemes schemes would well. I am thinking of something similar to this from Cuckoo Sandbox

![Screenshot from 2022-02-22 17-49-32](https://user-images.githubusercontent.com/657617/155190173-b1089957-08e4-4a27-b609-30cfcbce8ca3.png)

**Comment by oliverchang** [comment]
Is there any work remaining here?

**Comment by DavidKorczynski** [comment]
> Is there any work remaining here?

We have conclusions added now and they look good I recon. However, we should re-iterate over the language in the conclusions and also refine the actual conclusions (what we consider good, how we phrase "this could be improved" and things of this nature). I left this issue open for these purposes.

**Comment by oliverchang** [comment]
The current ones LGTM for v1. So removing the milestone.

**Comment by DavidKorczynski** [comment]
Closed by https://github.com/ossf/fuzz-introspector/pull/416
