### ISSUE TITLE
Only run CI when relevant

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#463]
The fuzzing part of the CI is triggered each time a PR is done. However, the fuzzing only targets the code in `src/`. We should avoid running the CI for PRs that change code or documentaiton not touched by the fuzzers.

**Comment by DavidKorczynski** [comment]
@arthurscchan could you take a look at this?

**Comment by arthurscchan** [comment]
Got it. Will look at it.
