### ISSUE TITLE
`./infra/helper.py build_fuzzers --sanitizer=introspector` fails with the vanilla OSS-Fuzz toolchain

### ISSUE THREAD

**Issue by evverx** [ossf/fuzz-introspector#483]
When projects fail to compile with FI OSS-Fuzz recommends running something like
```sh
Step #7 - "compile-libfuzzer-introspector-x86_64": To reproduce, run:
Step #7 - "compile-libfuzzer-introspector-x86_64": python infra/helper.py build_image ...
Step #7 - "compile-libfuzzer-introspector-x86_64": python infra/helper.py build_fuzzers --sanitizer introspector
```
locally and it always fails with
```sh
INFO:__main__:Logging level set
INFO:fuzz_introspector.utils:File: /out/llvm-symbolizer is executable
INFO:fuzz_introspector.utils:File: /out/fuzz-message is executable
INFO:fuzz_introspector.commands:Pairings: []
INFO:__main__:Ending fuzz introspector post-processing
INFO:__main__:Logging level set
INFO:fuzz_introspector.commands:[+] Loading profiles
INFO:fuzz_introspector.data_loader: - found 0 profiles to load
INFO:fuzz_introspector.commands:Found no profiles. Exiting
INFO:__main__:Ending fuzz introspector report generation
INFO:__main__:Ending fuzz introspector post-processing
ERROR:root:Building fuzzers failed.
```
because as far as I can tell the custom clang isn't used there.

**Comment by Navidem** [comment]
> because as far as I can tell the custom clang isn't used there.

That's right! For that purpose at least `base-builder:introspector` is needed to be pulled and used. Like steps here:
https://github.com/ossf/fuzz-introspector/tree/main/oss_fuzz_integration#build-with-existing-oss-fuzz-purposes

**Comment by DavidKorczynski** [comment]
To clarify, is your point that there should be some appropriate error message and perhaps not print all that stuff when it won't succeed?

**Comment by evverx** [comment]
I seem to have missed the notifications. Sorry about that.

This issue was mostly prompted by https://github.com/ossf/fuzz-introspector/pull/454#issuecomment-1217826923 (where various use cases were discussed) and as an OSS-Fuzz user I think ideally it should be possible to somehow use the OSS-Fuzz toolchain instead of replacing the OSS-Fuzz images with the FI images. Having said that I'm not sure how it can be implemented so probably OSS-Fuzz should point to https://github.com/ossf/fuzz-introspector/tree/main/oss_fuzz_integration#build-with-existing-oss-fuzz-purposes to make it easier to figure out what should be done to get
```sh
python infra/helper.py build_fuzzers --sanitizer introspector ...
```
to work.

**Comment by evverx** [comment]
Looks like now that https://github.com/google/oss-fuzz/pull/8868 and https://github.com/google/oss-fuzz/pull/8878 are merged this issue can be closed.
