### ISSUE TITLE
Per-fuzzer coverage report is not displayed completely

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#503]
The report page does not fully display the drop-down list of per-fuzzer coverage. The list is covered by table of content:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/19780488/189011143-af8c0252-3e3d-4f0b-87b0-e1c7964a8960.png">

To reproduce:
1) select a project with multiple fuzzer
2) click on "Per-fuzzer coverage"

**Comment by DavidKorczynski** [comment]
I can't reproduce -- is this from latest fuzz-introspector?

A similar issue was solved in https://github.com/ossf/fuzz-introspector/issues/457

**Comment by Navidem** [comment]
> A similar issue was solved in #457

Yes! it's duplicate of #457
