### ISSUE TITLE
per fuzzer coverage links broken in util-linux

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#598]
Ref: https://github.com/util-linux/util-linux/pull/1874#issuecomment-1308622017

On the util-linux project, the "per-fuzzer-coverage" links are broken:

We get this link: https://storage.googleapis.com/oss-fuzz-coverage/util-test_mount_fuzz/linux/reports-by-target/20221109/test_mount_fuzz/linux/report.html

Where the correct link is: https://storage.googleapis.com/oss-fuzz-coverage/util-linux/reports-by-target/20221109/test_mount_fuzz/linux/report.html

**Comment by DavidKorczynski** [comment]
Looks like it's because this substitution is too strong: https://github.com/ossf/fuzz-introspector/blob/28feb560444a8c94177a7bc558d9209fec2bcc08/src/fuzz_introspector/utils.py#L240-L244

**Comment by DavidKorczynski** [comment]
`.replace("/linux/", f"/{target_name}/linux/")` should fix this

**Comment by evverx** [comment]
I seem to have overlooked this. Thanks for noticing and fixing this!

**Comment by DavidKorczynski** [comment]
The fix for this was wrong:
There is no `/` after `linux` in the coverage url from OSS-Fuzz: https://github.com/google/oss-fuzz/blob/8b9cf2d081f5ae8d57847b9b20308dad645e8788/infra/build/functions/build_and_run_coverage.py#L306-L307
