### ISSUE TITLE
Link to per target coverage report

### ISSUE THREAD

**Issue by oliverchang** [ossf/fuzz-introspector#62]
We're looking at adding additional split-by-target coverage reports as part of https://github.com/google/oss-fuzz/issues/7015. 

We should link to that instead.

**Comment by oliverchang** [comment]
@Navidem are there any blockers here to doing this now?

**Comment by DavidKorczynski** [comment]
I have a thought here -- I think we should add a feature for selecting which coloring/links one would like. I find both project-wide and fuzzer-specific to be useful. We have pushed some interaction capabilities recently and having the ability to select coloring + links would fit well with that. @AdamKorcz do you have some thoughts here?

**Comment by oliverchang** [comment]
For the purposes of the v1 milestone, perhaps we can start simple here? Or is it not much more work at all to support this multipel coloring/links?

**Comment by Navidem** [comment]
#160 uses the per-target links for fuzzer details section.
It makes sense to link to per-target coverage when providing details on a specific fuzz target. For the overall project overview, total coverage link fits better.

**Comment by DavidKorczynski** [comment]
> For the purposes of the v1 milestone, perhaps we can start simple here? Or is it not much more work at all to support this multipel coloring/links?

let's start simple then we can configure it properly across the project such that the user can manage which coverage profile should be used in various places.

**Comment by Navidem** [comment]
closing this as #164 adds support for per-target coverage report to each fuzzer's report.
