### ISSUE TITLE
Add google analytics for oss-fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#623]
From https://github.com/google/oss-fuzz/issues/9039

**Comment by Navidem** [comment]
Do we have a timeline for this?

**Comment by AdamKorcz** [comment]
> Do we have a timeline for this?

By end of this week.

**Comment by Navidem** [comment]
Thanks!

**Comment by DavidKorczynski** [comment]
This is now fixed in https://github.com/ossf/fuzz-introspector/pull/671 -- if `G_ANALYTICS_TAG` environment variable is set with the relevant analytics tag, google analytics is enabled!

**Comment by DavidKorczynski** [comment]
todo: update fuzz introspector version on OSS-Fuzz and add an environment variable with the relevant tag when building introspector builds
