### ISSUE TITLE
Make call-tree collapsible

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#65]
Call-tree report is an important result currently fuzz introspector generates to show an overlay of coverage report on the control flow. 

For better user experience it is valuable to make call tree collapsible like at the call-depth level, so the user can decide how deep the graph should show.

![Screen Shot 2022-03-08 at 10 29 02 AM](https://user-images.githubusercontent.com/19780488/157303253-501589c7-a0e7-4dec-a92c-d51a128774bd.png)

**Comment by DavidKorczynski** [comment]
Fixed with https://github.com/ossf/fuzz-introspector/pull/72

Closing as it is collapsible now -- it needs further refinements though, tracking those here: https://github.com/ossf/fuzz-introspector/issues/73
