### ISSUE TITLE
unify oss-fuzz integrations

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#67]
Currently we have two oss-fuzz integrations: the integration upstream in oss-fuzz and the one local in fuzz-introspecctor. Ideally the one in OSS-Fuzz upstream should also be used locally here in fuzz-introspector. The only thing we really need from fuzz-introspector's perspective is some scripting to make it easy testing new developments locally

**Comment by DavidKorczynski** [comment]
@Navidem @oliverchang -- we now use the upstream OSS-Fuzz fuzz-introspector integration here as well. We still need a small bit of patching to support testing during development, so the main things we do in the patching is just adding support for copying in fuzz-introspector from the file system rather than cloning it from github.

Two additional changes that are currently needed in the patching :
- removing `--coverage-url` from the arguments to the post-processing: https://github.com/ossf/fuzz-introspector/blob/96b7aee16a40e54b788fecd5520de555a69211a7/oss_fuzz_integration/oss-fuzz-patches.diff#L21-L22
- avoiding launch of http server: https://github.com/ossf/fuzz-introspector/blob/96b7aee16a40e54b788fecd5520de555a69211a7/oss_fuzz_integration/oss-fuzz-patches.diff#L57-L58

will update the docs accordingly!

**Comment by DavidKorczynski** [comment]
> I don't know if OSS-Fuzz pulls the fuzz-introspector images locally when downloading the latest images?

Before I update the docs it might be nice to clarify this -- can users run fuzz-introspector locally using OSS-Fuzz without having to build images locally? When I run the following commands `base-clang` without introspector is used, which means the fuzz-introspector clang is not used and thus no results:
```
sudo docker system prune -a
git clone https://github.com/google/oss-fuzz
cd oss-fuzz
python3 infra/helper.py builder_fuzzers --sanitizer=introspector htslib
```

**Comment by DavidKorczynski** [comment]
> > I don't know if OSS-Fuzz pulls the fuzz-introspector images locally when downloading the latest images?
> 
> Before I update the docs it might be nice to clarify this -- can users run fuzz-introspector locally using OSS-Fuzz without having to build images locally? When I run the following commands `base-clang` without introspector is used, which means the fuzz-introspector clang is not used and thus no results:
> 
> ```
> sudo docker system prune -a
> git clone https://github.com/google/oss-fuzz
> cd oss-fuzz
> python3 infra/helper.py builder_fuzzers --sanitizer=introspector htslib
> ```
> 
> @Navidem

@Navidem @oliverchang -- do you know this? I assume users don't have the fuzz-introspector images locally without building the images themselves?

**Comment by Navidem** [comment]
>  can users run fuzz-introspector locally using OSS-Fuzz without having to build images locally?

I guess pulling base-clang:introspector and base-builder:introspector is enough and no need to re-build locally. Have not checked it to see it works end-to-end.

**Comment by oliverchang** [comment]
> I guess pulling base-clang:introspector and base-builder:introspector is enough and no need to re-build locally. Have not checked it to see it works end-to-end.

+1. Users can pull our pre-built introspector images to replace the vanilla base images.

**Comment by DavidKorczynski** [comment]
Sounds good -- thanks! Closing this

**Comment by DavidKorczynski** [comment]
We still rely on one patch in the fuzz-introspector build that is needed to run locally, without this patch running fuzz-introspector using oss-fuzz locally out of the box is hindered. 

https://github.com/ossf/fuzz-introspector/blob/1439477a724f2d8747840977ae4335fc48cbe96e/oss_fuzz_integration/oss-fuzz-patches.diff#L21-L22

See @MarcoFalke comment here https://github.com/ossf/fuzz-introspector/issues/48#issuecomment-1087513497
