### ISSUE TITLE
Sink analyser causing crashes on OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [ossf/fuzz-introspector#729]
A number of OSS-Fuzz projects are failing with the stack trace:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_introspector.analyses.metadata: - Running analysis MetadataAnalysis
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_introspector.analyses.metadata: - Completed analysis MetadataAnalysis
Step #6 - "compile-libfuzzer-introspector-x86_64": INFO:fuzz_introspector.analyses.sinks_analyser: - Running analysis SinkCoverageAnalyser
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 151, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     main()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 131, in main
Step #6 - "compile-libfuzzer-introspector-x86_64":     return_code = commands.run_analysis_on_dir(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/commands.py", line 103, in run_analysis_on_dir
Step #6 - "compile-libfuzzer-introspector-x86_64":     html_report.create_html_report(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/html_report.py", line 999, in create_html_report
Step #6 - "compile-libfuzzer-introspector-x86_64":     html_string = analysis_instance.analysis_func(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/analyses/sinks_analyser.py", line 369, in analysis_func
Step #6 - "compile-libfuzzer-introspector-x86_64":     reachable_function_list = self._retrieve_reachable_functions(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/analyses/sinks_analyser.py", line 242, in _retrieve_reachable_functions
Step #6 - "compile-libfuzzer-introspector-x86_64":     if callsite_str in function_callsites[func_name]:
Step #6 - "compile-libfuzzer-introspector-x86_64": KeyError: '_ZNSt11logic_errorC2EPKc'
```
It seems to happen on quite a number of a projects.

@arthurscchan did we fix this? See example logs:
- https://oss-fuzz-build-logs.storage.googleapis.com/log-9829781c-e232-42ef-ae01-09009deea913.txt
- https://oss-fuzz-build-logs.storage.googleapis.com/log-680667f3-a290-4325-82a2-a08367445b6a.txt
- https://oss-fuzz-build-logs.storage.googleapis.com/log-0d097980-e6fb-42d3-aae9-cb917c276ba8.txt

**Comment by arthurscchan** [comment]
Yes. This is cause by empty function_callsites result in key error. The whole _retrieve_reachable_functions has been removed in #712  and the logic has been changed in #728.

**Comment by DavidKorczynski** [comment]
Okay, do you know if the following projects are working: alembic, abseil-cpp, aspell, avahi ?

**Comment by arthurscchan** [comment]
abseil-cpp, aspell, avahi are working normally. But I experience build error for alembic as follows

`+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fprofile-instr-generate -fcoverage-mapping -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -stdlib=libc++ -std=c++11 -I /src -I /src/alembic/lib -I /work/build_alembic/lib -I /usr/local/include/OpenEXR /src/alembic_dump_info_fuzzer.cc /work/build_alembic/lib/Alembic/libAlembic.a -fsanitize=fuzzer -o /out/alembic_dump_info_fuzzer -lImath -lIex -lHalf
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
/work/build_alembic/lib/Alembic/libAlembic.a(IObject.cpp.o): in function `Alembic::Abc::v12::IObject::~IObject()':
IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x29a): undefined reference to `__asan_report_load1'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2a8): undefined reference to `__asan_report_load1'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2b0): undefined reference to `__asan_report_store8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2b5): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2ba): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2bf): undefined reference to `__asan_report_store8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2c4): undefined reference to `__asan_report_store8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2c9): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2d1): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2d9): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2de): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2e6): undefined reference to `__asan_report_load8'
/usr/bin/ld: /work/build_alembic/lib/Alembic/libAlembic.a(IObject.cpp.o):IObject.cpp:(.text._ZN7Alembic3Abc3v127IObjectD2Ev[_ZN7Alembic3Abc3v127IObjectD2Ev]+0x2eb): more undefined references to `__asan_report_load8' follow
/usr/bin/ld: /work/build_alembic/lib/Alembic/libAlembic.a(IObject.cpp.o): in function `Alembic::AbcCoreAbstract::v12::ObjectHeader::~ObjectHeader()':
IObject.cpp:(.text._ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev[_ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev]+0x104): undefined reference to `__asan_report_load1'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev[_ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev]+0x116): undefined reference to `__asan_report_load1'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev[_ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev]+0x11b): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev[_ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev]+0x120): undefined reference to `__asan_report_load8'
/usr/bin/ld: IObject.cpp:(.text._ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev[_ZN7Alembic15AbcCoreAbstract3v1212ObjectHeaderD2Ev]+0x128): undefined reference to `__asan_report_load8'
/usr/bin/ld: /work/build_alembic/lib/Alembic/libAlembic.a(IObject.cpp.o): in function `Alembic::Abc::v12::IObject::getHeader() const':
IObject.cpp:(.text._ZNK7Alembic3Abc3v127IObject9getHeaderEv[_ZNK7Alembic3Abc3v127IObject9getHeaderEv]+0x1e): undefined reference to `__asan_option_detect_stack_use_after_r`
