### ISSUE TITLE
textcov_reports for Java projects

### ISSUE THREAD

**Issue by Navidem** [ossf/fuzz-introspector#775]
PR https://github.com/google/oss-fuzz/pull/9208 was incomplete in terms of placing correct files in `textcov_reports` for Java project. 

We need `coverage` to place files in that directory which will be copied to the coverage bucket using cloud build, otherwise the Introspector build for Java fails.

**Comment by oliverchang** [comment]
@Navidem are you ablle to pick this up? Or is this something you can help with @DavidKorczynski ?

**Comment by Navidem** [comment]
I think I got it:

This is how java coverage is loaded in FI:
https://github.com/ossf/fuzz-introspector/blob/54584d2846119b6aead7731e7ce49b8115b979fd/src/fuzz_introspector/code_coverage.py#LL658C76-L658C86

So, the `coverage` will copy that file into `textcov_reports` like this line:

https://github.com/google/oss-fuzz/blob/7efd35c1f23e804e4f707eb0b51c9498c810daa3/infra/base-images/base-runner/coverage#L382

**Comment by Navidem** [comment]
This did the job: https://github.com/google/oss-fuzz/pull/9440/commits/9ba3411d3a5d46cec8ea7617a5e6e4e3e595139f
